Add ac4 patch to enable ATSC 3.0
jellyfin/jellyfin-ffmpeg pull request #128
Opened 2022-04-07 16:57 UTC by simcop2387

I don't expect this to actually get accepted, but wanted to make it for tracking purposes.  This adds the AC4 codec patch that exists to the ffmpeg used by jellyfin so that ATSC 3.0 support can be achieved.  I've tested this with my local install and an ATSC 3.0 broadcast and it works very well.  

This could be used while awaiting official support in FFMpeg in a future version, and I've created an amd64 .deb that I'm placing as a release on my fork for anyone who needs it.

2022-04-08 10:11 UTC, nyanmisaka requested changes
Name of the patch should be registered in https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/debian/patches/series

https://trac.ffmpeg.org/ticket/8349
I'd like to wait for the patch series to get into upstream first since the it's still WIP and it may break when we bump to ffmpeg 5.x, which has many API changes.

2022-04-08 10:11 UTC, nyanmisaka commented on debian/patches/ac4.patch
> ++                fcomp
`mpegts.c.orig` should be removed.

2022-04-08 10:11 UTC, nyanmisaka commented on debian/patches/ac4.patch
> ++++ jellyfin-ffmpeg-4.4.1/libavcodec/Makefile.orig
`Makefile.orig` should be removed.

2022-04-08 10:11 UTC, nyanmisaka commented on debian/patches/ac4.patch
> +Last-Update: 2022-04-07
These redundant descriptions can be removed. For example: https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/debian/patches/0001-add-fixes-for-segement-muxer.patch

2022-04-08 10:11 UTC, nyanmisaka commented on debian/patches/ac4.patch
> +--- jellyfin-ffmpeg-4.4.1.orig/libavcodec/Makefile
`-4.4.1` suffix should be removed.

2022-06-01 01:15 UTC, simcop2387 commented
Agreed about the changes, I can make them but I also agree that waiting for the switch to ffmpeg 5.x is better anyway.  The original patch on the trac link is actually made for ffmpeg 5 and i did some surgery to get it to apply to 4.4, which is why i made this.  for anyone who wanted to apply it earlier than waiting for that upgrade to happen.  If I find them time I'll fix this up so it's easier to apply and test.

2022-06-01 05:22 UTC, Shadowghost commented
If you didn't already see it: the codebase if Jellyfin-ffmpeg is now 5.x, so that should make things easier for you :)

2022-11-03 00:58 UTC, soxrok2212 commented
Is there any news on this? I live in an ATSC 3.0 market and am actively looking to transcode AC4 :)

2022-12-31 19:22 UTC, scott4290 commented
> Is there any news on this? I live in an ATSC 3.0 market and am actively looking to transcode AC4 :)

It looks like @nyanmisaka requested that @simcop2387 make some additional changes.  I was looking into how to get ac4 support into the ffmpeg base, and it looks like changes are discussed in the ffmpeg-devel email distro.

2023-08-24 17:33 UTC, soxrok2212 commented
There's another fork here: https://github.com/sub3/FFmpeg/commit/565c5ab0f8dac2711b46874cd3e32c6aebd23e90

I've yet to try it though, as I need to run a new coax to my HD HomeRun and my server is changing up a bit.

2023-09-15 01:41 UTC, Robert-D commented
I am also looking for AC4 support for ATSC 3. Any chance this will be merged in the near future? Sorry just bought a HDHomeRun Flex for the sole purpose of getting these channels, but can't hear them. Any resources you can point me to compile the ffmpeg from a working fork?

2023-09-15 03:02 UTC, Robert-D commented
> ...and I've created an amd64 .deb that I'm placing as a release on my fork for anyone who needs it.

Any way we can get a .deb package of the static build files for ffmpeg 5? I tried the release for version 4 on your fork, but when I selected the new location of the ffmpeg file inside jellyfin it gave me an error "We're unable to find FFmpeg using the path you've entered. FFprobe is also required and must exist in the same folder. These components are normally bundled together in the same download. Please check the path and try again."

2024-01-23 06:45 UTC, androidWG commented
Any update on this? Still not able to play ATSC tracks on Jellyfin

2024-01-23 07:18 UTC, Shadowghost commented
There are still no patches compatible with current FFmpeg versions. FFmpeg does only support remuxing of AC-4 streams at the moment.

2024-07-16 12:18 UTC, closed without merging