Add AV1 decoding support with dav1d
jellyfin/jellyfin-ffmpeg pull request #43
Opened 2020-06-18 02:05 UTC by RazeLighter777

Adds dav1d library support to jellyfin-ffmpeg. This will allow jellyfin-ffmpeg to transcode AV1 files to other codecs such as H.264. This addresses issue #39. I'm not experienced with debian packaging.

Note that this pull request does NOT allow transcoding to AV1, encoders for AV1 are not in a viable state currently. This allows playback of AV1 files by transcoding them from AV1 to another format.

(EX AV1 file -> dav1d -> x264 -> Jellyfin client)

2020-06-18 12:09 UTC, RazeLighter777 commented
Currently need to fix the static build, because all dependencies like libx265 and others were unintentionally linked statically. I assume this is not desired behavior.

2020-06-18 18:18 UTC, RazeLighter777 commented
Upon further review, I decided to use a shared library instead to prevent muddling the build configuration. Dav1d is compiled and included as a shared library with jellyfin-ffmpeg.

2020-06-27 20:00 UTC, RazeLighter777 commented
@joshuaboniface 
@nvllsvm 
My changes are ready for review. To build, use command `./build [distro] [arch]` and the packages will be placed in `../bin/jellyfin-ffmpeg-whatever.deb`

2020-06-29 16:02 UTC, nyanmisaka requested changes

2020-06-29 16:02 UTC, nyanmisaka commented on docker-build.sh
> +    # Download and install dav1d
`prepare_hwa_amd64()` only prepares files for x86. If so, `--enable-libdav1d` should also be placed in `CONFIG_x86`. Or put these code in a place behind to suit arm64 and armhf.

2020-07-03 19:51 UTC, RazeLighter777 commented on docker-build.sh
> +    # Download and install dav1d
changes addressed. I moved the build option to x86 only.

2020-07-12 22:46 UTC, RazeLighter777 commented
I am at boot camp and am unable to work on this pull request for the next month.

2020-07-18 07:07 UTC, joshuaboniface approved these changes
So far this looks good to me, I see no issues with it from a license or build standpoint, and it seems to build fine.

2020-07-18 07:07 UTC, merged